### ISSUE TITLE
Test before stable release

### ISSUE THREAD

**Issue by firstred** [firstred/mdstripe#23]
- [x] 1.6.1.0
- [x] 1.6.1.1
- [x] 1.6.1.2
- [x] 1.6.1.3
- [x] 1.6.1.4
- [x] 1.6.1.5
- [x] 1.6.1.6

**Comment by kpodemski** [comment]
I think you should focus on 1.6.1 and above, people need to understand that software needs to be updated

**Comment by firstred** [comment]
:+1: :smile:

**Comment by kpodemski** [comment]
If so you can pass array to `registerHook` method ;)

https://github.com/firstred/mdstripe/blob/dev/mdstripe.php#L107

small but convenient

**Comment by firstred** [comment]
Nice. Thanks! I didn't know that.
