### ISSUE TITLE
error message handing - wrong exp card date

### ISSUE THREAD

**Issue by adamus007p** [firstred/mdstripe#27]
I see other "error":
 
I add 4GBP and voucher -10%, then I put my card and wrong exp date.
 
12 / 16
 
it should be 
 
11 / 16
 
 
The field with date are red, but with no error message.
![stripe6](https://cloud.githubusercontent.com/assets/19956106/16094711/ca0c57c0-3341-11e6-80e9-dd119cbaad6f.png)

**Comment by firstred** [comment]
This cannot be fixed by the module. It is part of Stripe's checkout form, which cannot be altered.
