### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by adamus007p** [firstred/mdstripe#28]
logo is resized not correct

default prestashop logo is rectangle

Stripe use square logo.

Maybe add a feature to add other square logo or use logo from Stripe
![stripe7](https://cloud.githubusercontent.com/assets/19956106/16094838/4fb45d14-3342-11e6-8407-252a49367b36.png)
?

**Comment by firstred** [comment]
Thanks for opening the issue. I forgot to add it to the todo list!
