### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by adamus007p** [firstred/mdstripe#29]
"Yes, the redirection is normal. The user should be redirected in order to actually charge the card."

After where there is no enough funds on the card there is a redirection.

In my case I am redirected to this page
http://www.tiikoni.c...iew/?id=c434239
 
Then customer need to go to card and go through all steps to be again in select payment step.
 
 
I think about customer experiences and payment flow.
 
If it would be error on popup or on the same page there the customer is putting card details it would be better from merchant and customer perspective.
 
Min. is to give more info on with error to guide the customer.
Customer is an idiot and don't know what to do.
 
 
1. other error management on the same page
 
or as min better guidance
 
Your card has insufficient funds. Please try to use other card or make sure that you have funds on your card.
 
Please go back to order steps and back to your payment options.
 
or contact us (link/email)
 
 
It is my suggestions.

////

I think that a simple "Go back" button would be sufficient and the best way to implement it, but will also have to take PrestaShop 1.7 into account nowadays.

////

Possible but it will takes a year when it will be safe to move to 1.7.

Go back button it is good idea.

**Comment by firstred** [comment]
For now just added a go back button. Order confirmation pages and error pages will always have to be manually changed by the merchant and luckily the module allows for that. Just add your theme optimized templates to the folder /themes/`theme name`/modules/mdstripe and you'll be good to go.
