### ISSUE TITLE
Informaction for the customers about the Stripe module

### ISSUE THREAD

**Issue by adamus007p** [firstred/mdstripe#30]
I would add a info for customers, what it a Stripe and which payment options/ cards / currency are available.

From Stripe:
https://support.stripe.com/questions/which-cards-and-payment-types-can-i-accept-with-stripe
I would insert some text like this one:

Pay by Stripe. 
 
We accept almost almost any kind of credit or debit card:

Visa, MasterCard, American Express, JCB, Discover, and Diners Club.

From any country (customers anywhere in the world) and any currency (pay by you local currency).

We also support Bitcoin, Apple Pay, Android Pay, and China’s Alipay.

and add some supported logos:

LOGOS:
https://support.stripe.com/questions/do-you-provide-logos-for-the-credit-card-types-we-can-accept

http://www.iconshock.com/credit-card-icons/
http://www.iconshock.com/icon_sets/wp-content/uploads/2011/03/credit_256px.jpg
http://thermosiv.com/wp-content/uploads/stripe-payments.png?v=7516fd43adaa

**Comment by firstred** [comment]
Not sure if this should be done by the module.

PrestaShop 1.6 has enough places in the theme itself and PrestaShop 1.7 allows you to add a text in the column at the right on the checkout page.

**Comment by firstred** [comment]
Apple Pay and Android Pay are not available, yet. It's expected that they will be available in Q3
