### ISSUE TITLE
build in module

### ISSUE THREAD

**Issue by adamus007p** [firstred/mdstripe#31]
It would be nice if there would be possibility to choose:

popup module like present one and add a build in version, that customers can see and put immediately card details.

It could be beneficial for the conversion.
Is someone will be afraid to click on popup to insert card details will be able to see fields to insert cards details immediately on the payments step in Prestashop.

**Comment by firstred** [comment]
The aim of the module is to keep it simple at first and should for now only use the Stripe checkout form which can only be shown as a popup.

It's a nice feature, but doesn't have a high priority ATM.

**Comment by firstred** [comment]
This looks like a good candidate to use for the credit card form: https://github.com/myg0v/Simple-Bootstrap-Stripe-Payment-Form

Currently stripe.js also supports Bitcoins, but that would require some more work.

**Comment by firstred** [comment]
Starting to look good:
![stripejsform](https://cloud.githubusercontent.com/assets/6775736/18573621/5ad75a7c-7bc5-11e6-94b5-4bf230db67f3.png)
