### ISSUE TITLE
https in order step

### ISSUE THREAD

**Issue by adamus007p** [firstred/mdstripe#34]
Hi mate,

In order step, there is a mixed content warning. In Chrome I can see:
Mixed Content: The page at 'https://www.shop.com/order' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://www.shop.com/module/mdstripe/validation'. This endpoint should be made available over a secure connection.

**Comment by firstred** [comment]
Hmmz, thanks for the info. I'll check the links that are being generated by PrestaShop.

I assume that you have been using mixed SSL and non-SSL pages? So "Force SSL on all pages" has been disabled?

**Comment by adamus007p** [comment]
Yes you are right.

Enable SSL YES
Force the SSL on all the pages  NO

yes links are genereated by Presta

**Comment by firstred** [comment]
Yeah, it sounds like a bug I often have made. I always assume that PrestaShop knows what to do, but if it determines that a page can be served without SSL (really no idea what determines that), then it will link to an insecure page.
It's much better to use something like:
`$link->getModuleLink('mdstripe', 'controller', array(), Tools::usingSecureMode());`
This basically means: if I'm using SSL now, the link should start with `https://`

**Comment by adamus007p** [comment]
$link->getModuleLink($this->name, 'validation',array(),null,null,null,true),
