### ISSUE TITLE
logo error

### ISSUE THREAD

**Issue by adamus007p** [firstred/mdstripe#35]
In order step I see error:

GET inner-5gVLccpGmDOuxKbhJy5g.js:5 GET https://checkout.stripe.com/api/color?image_url=https%3A%2F%2Fwww.shop.com%2Fimg%2Flogo.jpg&key=&locale= 404 (Not Found)

Chrome > developer tools > security

**Comment by firstred** [comment]
Maybe the shop image has not been generated properly. I need to see if I can reproduce it.

**Comment by adamus007p** [comment]
how can I contact you on priv?

**Comment by firstred** [comment]
Presta forum?

**Comment by firstred** [comment]
Does `1.0.5` fix it for you?

**Comment by adamus007p** [comment]
Unfortunately not.
I have now Stripe v1.0.5 - logo still is with wrong size.

**Comment by firstred** [comment]
I can't reproduce it with the information you have given me. Looks like a misconfigured server.
