### ISSUE TITLE
failed payment notification

### ISSUE THREAD

**Issue by adamus007p** [firstred/mdstripe#36]
I have noticed that there is no email when there will be a failed payment

It would be worth to add this option.

**Comment by firstred** [comment]
No email?

Hmmz, I've never seen a payment module do that. Do you have an example?

**Comment by adamus007p** [comment]
I had situation on production that customer wanted to purchase something and choose Stripe, there was an error. No funds, but I did not received any email.

I did not check if there was info in order, but it would be good feature when payment is not valid = sent email to merchant, that can contact with customer.

Try have not enough funds on card and make a payment.

I know that you can check BO> orders or Stripe but something it makes too much effort.

**Comment by acs-ferreira** [comment]
You can use Webhooks to accomplish that. See

https://stripe.com/docs/recipes/sending-emails-for-failed-payments

**Comment by firstred** [comment]
Interesting. I'll have a look at it!

I think that in that case it could be as simple as:
- Receive webhook
- Generate cart link
- Send mail with info and cart link

**Comment by adamus007p** [comment]
Hello Michael I would add a email notify for a merchant.

or and email to customer with error code, but more friendly explanation.
I saw on stripe such table: error code, explanation, solution.

It could be also implemented on FO side.

I think this would increase a sales.
