### ISSUE TITLE
PHP Fatal error:  Undefined class constant 'COLLECT_BILLING'

### ISSUE THREAD

**Issue by brrrrrrrt** [firstred/mdstripe#39]
when i try to pay with Stripe i get:

> PHP Fatal error:  Undefined class constant 'COLLECT_BILLING' in modules/mdstripe/controllers/front/eupayment.php on line 64

**Comment by firstred** [comment]
Fix: https://github.com/firstred/mdstripe/commit/641ca35d3ca871f380c70a065bd75fbe0027442e
