### ISSUE TITLE
TLS v1.2 is not supported. Please upgrade your server.

### ISSUE THREAD

**Issue by wajdiben06** [firstred/mdstripe#41]
Hi,
Thanks for this open source plugin.
But I have a problem, I have TLS 1.2 in my website godill.com but in the backoffice I have this error message "TLS v1.2 is not supported. Please upgrade your server." so I cannot activate the module : Is there a solution to resolve this problem ? Thanks, Regards

**Comment by firstred** [comment]
Yes, upgrade the cURL plugin: http://php.net/manual/en/book.curl.php

**Comment by wajdiben06** [comment]
Ok thanks for fast help :+1:
