### ISSUE TITLE
Payment shows wrong currency

### ISSUE THREAD

**Issue by brrrrrrrt** [firstred/mdstripe#42]
![bildschirmfoto von 2016-08-16 17-48-57](https://cloud.githubusercontent.com/assets/4489013/17705742/ca971446-63d9-11e6-9bd8-9b6df1edfd4e.png)
![bildschirmfoto von 2016-08-16 17-49-13](https://cloud.githubusercontent.com/assets/4489013/17705744/ccb8ba04-63d9-11e6-9d7b-59768c7cbaef.png)

the order total was 3 153,75 CZK but the stripe module prints  3 153,75€ - **i really hope the customer only payed 3 153,75 CZK and not 3 153,75€** that would be really bad.

**Comment by firstred** [comment]
What is your currency symbol? It displays the currency symbol from the currency that is linked to the order.

**Comment by brrrrrrrt** [comment]
the currencysymbol was Kĉ but it was displayed as K? on the invoice so i changed the Symbol to "CZK"

**Comment by brrrrrrrt** [comment]
In the orders table the currency of this order is "4" which is "Czech koruna" with the sign CZK it looks good on the the invoice, only stripe displays €

**Comment by firstred** [comment]
Is euro your default currency?

**Comment by brrrrrrrt** [comment]
Yes

**Comment by firstred** [comment]
Looks like the module only displays the default currency in the transactionlist. I can't find any logic that reads the info of the actual orders in order to detect the currency symbol.

I think that my original idea was to convert everything to default currency in this list, but the module never actually converts the amount. This needs to be implemented, but of course the module can display the original currency of the orders. What do you think is a good option?

**Comment by brrrrrrrt** [comment]
Sure! Displaying the Currency of the order would be fully ok.

**Comment by firstred** [comment]
Nice. Let's do that in a future update.

**Comment by brrrrrrrt** [comment]
Great!
Other payment modules have the option to choose which currency are activated for that payment option. My customer prefers to limit all payments to the default currency and have currencies just for "orientation purposes" - would be "nice" to have that option with stripe too but this may be a different issue...

**Comment by brrrrrrrt** [comment]
i tried to have a look, but unfortunally  i do not understand how this all works :( http://doc.prestashop.com/display/PS16/Using+the+HelperList+class says:

```
 ['currency'] => {true, false},    // If set and type == price, the currency displayed
                                   // will use the item currency and not the default currency (optional).
```

when i add:

>  'currency' => true

at line nr. 1287 in mdstripe.php
nothing happens :(  maybe a prestashop bug ?

**Comment by firstred** [comment]
No, just lack of documentation ^^

If I follow PrestaShop logic, I think that there needs to be an additional column in the list called 'currency' and has to contain the iso code, I think.

We can quickly initialize that by inner joining the Transaction table with the Orders table, then the Currency table and take the ISO code from that table.

**Comment by brrrrrrrt** [comment]
ah, you mean, by now the "item" has no currency, and that is why the setting has no effect?

**Comment by firstred** [comment]
Yeah, I think that's the cause

**Comment by brrrrrrrt** [comment]
still no luck by adding:

>         $sql->innerJoin('orders', 'o', 'st.`id_order` = o.`id_order`');
>         $sql->innerJoin('currency', 'c', 'o.`id_currency` = c.`id_currency`');

to function getTransactionsByOrderId in classes/StripeTransaction.php

tried with select('*') and with:

`select('st.id_stripe_transaction,st.id_order,st.type,st.source,st.card_last_digits,st.id_charge,st.amount,st.date_add,st.date_upd,c.iso_code as currency');`

and also:
`select('st.id_stripe_transaction,st.id_order,st.type,st.source,st.card_last_digits,st.id_charge,st.amount,st.date_add,st.date_upd,c.id_currency as currency');`

i think i should give up "happy hacking" and let do it someone who knows what he is doing ;)

**Comment by firstred** [comment]
Hmmz, I'll try to figure it out when I find the time. So for now, try to remember that the currency in the transaction list might be different :stuck_out_tongue_winking_eye:

**Comment by firstred** [comment]
Thanks for your help!

**Comment by brrrrrrrt** [comment]
no worries, so far its just a "display error", everything is fine, not that urgent :D

**Comment by firstred** [comment]
Hmmz, it has never been implemented. Setting `currency` to `true` does nothing.
The module should just format the string in the results array :/
