### ISSUE TITLE
Not Available in Payment Options

### ISSUE THREAD

**Issue by TwassistantKeith** [firstred/mdstripe#43]
Hello, I am unable to select this module as an active payment module:

http://screencast.com/t/3zxboia8

And it is not appearing as a payment option (I have no available payment options).

Perhaps it is related to the fact that I can't select currency restrictions?

http://screencast.com/t/GqINeb6IHOV

Thanks for your help!

**Comment by firstred** [comment]
Thanks for opening the issue 

The currency restriction array should indeed be initialized in the payment module. Will do in the next version.

Not sure if this payment module will ever show up on the active payment modules list. I don't pay PrestaShop to promote this module.

**Comment by brrrrrrrt** [comment]
> Not sure if this payment module will ever show up on the active payment modules list. I don't pay PrestaShop to promote this module.

how stupid is that? let a developer pay for basic functionality :(  

if it would be for the "featured payment options list" i would say this ok, this may have something to do with promotion, but for the "list of active payment options" - to me this is basic functionality/usability - force USERS to search within the modules section, to be able to access the stripe settings when there is a "Modules -> Payment Options" page - that is going way to far, imho

**Comment by firstred** [comment]
Note to self: looks like
```php
        $this->is_eu_compatible = 1;
        $this->currencies = true;
        $this->currencies_mode = 'checkbox';
```
needs to be set before calling the parent constructor. Gotta love PrestaShop dev docs :/

**Comment by firstred** [comment]
Even managed to make the module trusted: https://github.com/firstred/mdstripe/commit/fe25bd24676ade7dc64975257b31390c31fd813f
