### ISSUE TITLE
Support Apple Pay

### ISSUE THREAD

**Issue by firstred** [firstred/mdstripe#46]

**Comment by firstred** [comment]
Postponed. Cannot test :(

**Comment by renaudpro** [comment]
I have in iPhone i can test ?

**Comment by firstred** [comment]
Thanks, but we're going to need more.

Do you have an Apple Developer account in a supported country: https://stripe.com/apple-pay ?

And I hope you don't mind having to test for about a hundred times :stuck_out_tongue_winking_eye:

**Comment by renaudpro** [comment]
I have not Apple Developper account :( .

No no :)

**Comment by firstred** [comment]
Hmmz, I'll ask around then.
