### ISSUE TITLE
Error TLS 1.2

### ISSUE THREAD

**Issue by auf-ins-internet** [firstred/mdstripe#48]
My Module version is v1.0.12. TLS 1.2 is running on my server. Test is OK. But payment is impossible. Error:

Stripe no longer supports API requests made with TLS 1.0. Please initiate HTTPS connections with TLS 1.2 or later. You can learn more about this at https://stripe.com/blog/upgrading-tls.

![test](https://cloud.githubusercontent.com/assets/22956666/19556356/12bd005e-96c1-11e6-9b63-d29ce45f434c.jpg)
![result](https://cloud.githubusercontent.com/assets/22956666/19556361/173634de-96c1-11e6-86c2-8b89ff7b9da2.jpg)

Browser Firefox and Chrome, newest version, support TLS 1.2.

**Comment by firstred** [comment]
Hi,
The module already enforces TLSv.1.2, please check this page for more info: https://github.com/stripe/stripe-php#ssl--tls-compatibility-issues
