### ISSUE TITLE
The class returned must implement HookContentClassInterface

### ISSUE THREAD

**Issue by ludohenin** [firstred/mdstripe#50]
Since 1.7-RC2 (stil true for RC3) I'm getting this error

```
Exception in HookFinder.php line 78:
The class returned must implement HookContentClassInterface
```

message when enabling this module and navigating to the checkout page.

**Comment by Quetzacoalt91** [comment]
Hello @ludohenin,

Your issue does not seem to be related to the module, but to the core.
May I ask you to find the following PR and let me know if it fixes the issue ? https://github.com/PrestaShop/PrestaShop/pull/6836

Best regards

**Comment by ludohenin** [comment]
@Quetzacoalt91 yes it fixes it. Thanks for pointing this out.
