### ISSUE TITLE
CC Input fields not popping up

### ISSUE THREAD

**Issue by brrrrrrrt** [firstred/mdstripe#51]
just upgraded to 1.6.1.8 when testing the site i noticed on checking out the popup is not opening.

i need to click "Pay with Stripe" to open it. you can see the behavior here: https://shop.alpenheat.com

![bildschirmfoto von 2016-11-03 12-26-17](https://cloud.githubusercontent.com/assets/4489013/19964254/09918116-a1c1-11e6-9b37-75eabac82ca6.png)

**Comment by brrrrrrrt** [comment]
any updates on this, or is it just me having this issue?

**Comment by brrrrrrrt** [comment]
as a workaround (ugly hack) it works when adding a simulation of clicking the button in views/templates/front/eupayment.tpl right before the  </script>:

`      $(document).ready(function(){
         $('#mdstripe_payment_link').trigger('click');
      });
`

**Comment by brrrrrrrt** [comment]
the problem persists also after upgrading to 1.6.1.9

**Comment by firstred** [comment]
I changed the behavior. Let me know if 1.0.13 solves it.

**Comment by brrrrrrrt** [comment]
nope, i am sorry :( behavior is still the same, tested in FF and Chrome

**Comment by firstred** [comment]
Alright, let's update it.
