### ISSUE TITLE
Modify wrong code

### ISSUE THREAD

**Issue by coriaweb** [firstred/mdstripe#52]
Forgive my translation, I use google translator.

I checked that there is an error in the list of payment methods, this module breaks the design, I have corrected it to appear like the others.

* modules/mdstripe/views/templates/hook/payment.tpl

Line 39 - `<div class="col-xs-12 col-md-12">`

Change: 

Line 39 - `<div class="col-xs-12 col-md-6">`

* modules/mdstripe/views/css/front.css

Line 20 - `padding: 10px 10px 10px 10px;`

Change: 

Line 20 - `padding-left: 17px;`

Result: https://i.gyazo.com/69dd96bff19cd1292b88ee3322684517.png

**Comment by firstred** [comment]
You're not using the default theme, so that is to be expected. You can copy the module templates and CSS files to your theme folder and edit them from there, just like the rest of the modules.
