### ISSUE TITLE
Regressions on order last step - Apple Pay logo displayed but I don't want

### ISSUE THREAD

**Issue by GreggFr** [firstred/mdstripe#56]
This morning the module autoupdated :-(
So I lost some modifications I made in templates...
And I order last step, I can see payment logos, apple pay logo, even if I said No on the module configuration page.

Here is a screenshot.
![mdstripe_bad_display](https://cloud.githubusercontent.com/assets/24435844/20971790/084ce2e0-bc93-11e6-9c83-d7b1e567c347.png)

**Comment by firstred** [comment]
Does this fix it for you?
[mdstripe.zip](https://github.com/firstred/mdstripe/files/636970/mdstripe.zip)

**Comment by GreggFr** [comment]
No.
Apple pay still displayed.

**Comment by GreggFr** [comment]
I want to add that I would like to hide mdstripe-bootstrap and only display stripe checkout.
Maybe it should be configurable in admin module page.
