### ISSUE TITLE
Question: Why is payment.tpl and ccpayment.tpl shown on payment page?

### ISSUE THREAD

**Issue by fahu** [firstred/mdstripe#58]
Hi, I'm sorry for abusing the Issues page for that question but I found no other way to ask this question. I'm using your module but I don't understand why payment.tpl and ccpayment.tpl is shown on the payment page? The payment page is for displaying the different payment providers and not entering already entering the credit card credentials?

Best regards

**Comment by firstred** [comment]
A hard separation between the payment types is still being worked on. For now just a JavaScript "blockade" if an option is not available.

**Comment by fahu** [comment]
In case somebody else needs a quick solution for this: I just created an empty override for ccpayments.tpl file in the themes folder.

**Comment by gromatl** [comment]
For myself I just disabled the auto-update and directly edit line 1386 of mdstripe.php 
`return $this->display(__FILE__, 'views/templates/hook/payment.tpl').$this->display(__FILE__, 'views/templates/hook/ccpayment.tpl');`

now its like that : 
`return $this->display(__FILE__, 'views/templates/hook/payment.tpl');`
