### ISSUE TITLE
Payment form always displayed

### ISSUE THREAD

**Issue by alexchuin** [firstred/mdstripe#60]
Hello,

I've set the "Enable Stripe credit card form" option to NO but the stripe form is ALWAYS displayed in the checkout page.
The "Enable credit card animation" works fine.

Thanks for your plugin !
Alex

**Comment by firstred** [comment]
Thank you for the info! It's fixed in 1.0.14 which I would like to release
in an hour.

**Comment by alexchuin** [comment]
Top, thanks !

**Comment by firstred** [comment]
Updated
