### ISSUE TITLE
compatibility with 1.6.1.10

### ISSUE THREAD

**Issue by adamus007p** [firstred/mdstripe#62]
Hello,
Please have a look if your module is compatible with PrestaShop v1.6.1.10 Stable or there is some problem with my presta. I have noticed after update a problem.

I was wondering if there is a problem with suppession problem, because of update of the browser.

I have noticed that the modules has been updated but I did not made any updates.

Is there any auto update? Few times I have notices there there was info about update from stripe - a notice.

Now I will investigate the module and check it on git.

**Comment by adamus007p** [comment]
It seems that it auto update....

**Comment by firstred** [comment]
Yes, it's compatible. Please post a full bug report if you find anything. Thanks!
