### ISSUE TITLE
stripe not workrs

### ISSUE THREAD

**Issue by adamus007p** [firstred/mdstripe#63]
I can confirm that stripe autoupdate itself and with update it stops working.

Maybe it is connected with version 1.6.1.10, but maybe it is not an issue.

Module delete GIT files.

**Comment by firstred** [comment]
Disable auto update is you modified the module directly.

**Comment by adamus007p** [comment]
Hello Micheal please let me know if in your cache module is working with 1.6.1.10?

For me even newest version is not working.
I am clicking the button stripe and nothing appear.
