### ISSUE TITLE
Can't find this module at checkout

### ISSUE THREAD

**Issue by MatrixCoder01** [firstred/mdstripe#64]
Hello , i can see all Payment modules except this one at cashout.

**Comment by firstred** [comment]
More info?

**Comment by MatrixCoder01** [comment]
@firstred Thanks for you answer , what info can i provide?

**Comment by firstred** [comment]
What have you tried already?
You can configure the availability of payment modules in PrestaShop. You do know that, right?

**Comment by MatrixCoder01** [comment]
Already tried almost everything found on google , I can see it in active payment method . Enabled Dev mode no error

**Comment by MatrixCoder01** [comment]
Was thinking :
Is possible that if module is english and i use italian it doesn't show up?

**Comment by Clyde-B** [comment]
Hi,

I hope this is the right spot as I believe I have a similar issue. the module is installed but PrestaShop v 1.6 says "no payment modules installed" https://puu.sh/sVESx.png (screenshot)

**Comment by firstred** [comment]
Did you enable one of the options on the module's configuration page (Stripe checkout, Stripe CC form and/or Apple Pay) ?

**Comment by Clyde-B** [comment]
yes

**Comment by firstred** [comment]
Which one?

**Comment by Clyde-B** [comment]
Apple Pay and Stripe Checkout

**Comment by firstred** [comment]
Which PrestaShop version?

**Comment by Clyde-B** [comment]
1.6 i found an alternative but i don’t like it. so hopefully we can get this resolved

**Comment by firstred** [comment]
Managed to reproduce it on a Vanilla 1.6.1.10. I'm currently investigating...

**Comment by Clyde-B** [comment]
awesome.

**Comment by firstred** [comment]
The module doesn't hook to `displayPayment` anymore during the installation. You can fix this by manually hooking the module to `displayPayment` on the page "Modules and Services > Positions"

**Comment by Clyde-B** [comment]
i’m no pro but let me give this a shot

**Comment by Clyde-B** [comment]
still the same.

included the hook https://puu.sh/sWF7R.png <https://puu.sh/sWF7R.png>

but at checkout https://puu.sh/sWF9w.png <https://puu.sh/sWF9w.png>

**Comment by firstred** [comment]
That's not the right Stripe module.

**Comment by Clyde-B** [comment]
my mistake I see the difference https://puu.sh/sWFqX.png

I do have the plugin installed let me try moving to displayPayments

**Comment by Clyde-B** [comment]
ok. 

rookie alert!!

how do i move it?

**Comment by Clyde-B** [comment]
i got it! https://puu.sh/sWGqM.png

**Comment by firstred** [comment]
Nice!
