### ISSUE TITLE
Network error [errno 35]: Unsupported SSL protocol version

### ISSUE THREAD

**Issue by fabilo** [firstred/mdstripe#65]
Hi team, there's a bug that pops up on some hosting configurations where the module fails to connect to the Stripe API, error: Network error [errno 35]: Unsupported SSL protocol version.
Read more here: https://github.com/stripe/stripe-php/issues/289

Apparently the solution has been resolved with php-stripe version 4.0. Are we able to update to use a more recent version (current v4.3)

**Comment by firstred** [comment]
Thank you for opening the issue!

I'll update the library and test if it still works and if it does I'll include it in the next version.

**Comment by adamus007p** [comment]
I did not tested 1.0.17, but remember to turn off auto update in the module.

I stay with order version, because in my case the newest version was not working too.

**Comment by firstred** [comment]
That's like the worst thing you can do right now!
There's a reason why this module has been updated several times in the past week ;)

If you're having some critical issues with the module, please don't hesitate to post a detailed bug report in this issue section. I keep monitoring several production environments to see how the updates go, but every system is different.
