### ISSUE TITLE
ZipCode/PostCode verification

### ISSUE THREAD

**Issue by MatrixCoder01** [firstred/mdstripe#66]
Not asking for ZIP at checkout

**Comment by firstred** [comment]
Did you type the credit card number first? It depends on the card whether Stripe wants to show it or not:
![ccnumberfirst](https://cloud.githubusercontent.com/assets/6775736/21454357/29e59744-c918-11e6-9c35-ceda9997dca4.png)

**Comment by MatrixCoder01** [comment]
Yes tryed to type, ah ok didn't know that . Thank you !
