### ISSUE TITLE
No redirection for payment - Presta 1.7

### ISSUE THREAD

**Issue by ToDestiny** [firstred/mdstripe#67]
Dear Sir/Madam,
 
I am trying to use your Stripe module on my shop but it seems that I encounter a problem after the configuration.
 
I run on 1.7 Prestashop and I see your module without problems but it doesn’t work when I try to use it on my website. I am not so sure on what to do.
 
It works and I see the page where I pay, but when I click on Pay with Stripe, nothing happens. It seems that the link is the wrong one, guess it should be a link to the gateway but instead I have www.polinea.com/order (my website is in French but the link is this one in English)

![image](https://cloud.githubusercontent.com/assets/24790975/21497887/4d1efb2a-cc28-11e6-83d0-25ba68e815f9.png)
![image](https://cloud.githubusercontent.com/assets/24790975/21497892/561b47ce-cc28-11e6-90e4-4b50bc0a980d.png)
![image](https://cloud.githubusercontent.com/assets/24790975/21497893/5b208be4-cc28-11e6-8ee8-b1ef5c57100f.png)
![image](https://cloud.githubusercontent.com/assets/24790975/21497901/60e384e6-cc28-11e6-9976-9a5f280b9a2b.png)

 
![image](https://cloud.githubusercontent.com/assets/24790975/21497908/68aa9264-cc28-11e6-850c-d1181a05d9d1.png)

I am not sure what I did wrong...
 Thank you in advance!

**Comment by firstred** [comment]
When you open up Chrome's Developer Tools (https://developer.chrome.com/devtools), do you see any JavaScript errors (red text) ?

**Comment by ToDestiny** [comment]
Thank you for coming back to me,

No problems on JavaScript but 505 error when redirecting (see picture
attached)

Did I do something wrong?

Sincerely,
ᐧ


Anthony Colas
+33 7 82 66 98 09
Email : AnthonyColas.France@gmail.com
Skype: anthony_colas

2016-12-27 14:36 GMT+01:00 Michael Dekker <notifications@github.com>:

**Comment by ToDestiny** [comment]
I let the module ON if you would like to check.

http://www.polinea.com/module/mdstripe/validation

Thank you
ᐧ


Anthony Colas
+33 7 82 66 98 09
Email : AnthonyColas.France@gmail.com
Skype: anthony_colas

2016-12-27 21:00 GMT+01:00 Anthony COLAS <anthonycolas.france@gmail.com>:

**Comment by firstred** [comment]
HTTP 505 error is a server problem: https://httpstatuses.com/505

I suggest you have a look at your web server configuration and fix the error, because there's nothing I can do from the module to prevent it from happening.
