### ISSUE TITLE
PHP Fatal error:  Call to undefined method MdstripeEupaymentModuleFrontController::getShopId

### ISSUE THREAD

**Issue by brrrrrrrt** [firstred/mdstripe#68]
after upgrading to 1.0.17 i get a 500 Error on checkout (/module/mdstripe/eupayment):

`PHP Fatal error:  Call to undefined method MdstripeEupaymentModuleFrontController::getShopId() in /.../modules/mdstripe/controllers/front/eupayment.php on line 96`

using prestashop 1.6 on PHP 5.6

**Comment by firstred** [comment]
Man, I hate that checkout :stuck_out_tongue_winking_eye:

**Comment by brrrrrrrt** [comment]
sorry! :dagger:

**Comment by firstred** [comment]
But I could have seen this before :open_mouth: 
![undefinedvarshopid](https://cloud.githubusercontent.com/assets/6775736/21692499/792ca120-d37d-11e6-82b8-1d9d22c36b9e.png)

**Comment by firstred** [comment]
replacing with 
```
'stripeShopThumb' => $this->context->link->getMediaLink('/modules/mdstripe/views/img/shop'.$this->context->shop->id.'.jpg'),
```
will do

**Comment by brrrrrrrt** [comment]
yes! you are the man! 

thanks alot!
 :dancer:

**Comment by firstred** [comment]
Verified working again here. You?

**Comment by firstred** [comment]
Kewl, thanks for testing!
